@echo off
setlocal enabledelayedexpansion
title Claude DeepSeek Proxy - Setup

:: =============================================================================
:: Claude → DeepSeek Proxy - Interactive Setup (Windows)
:: =============================================================================

:: ── Paths ───────────────────────────────────────────────────────────────────
set "SCRIPT_DIR=%~dp0"
set "ENV_FILE=%SCRIPT_DIR%.env"
set "CERTS_DIR=%SCRIPT_DIR%certs"

:: ── Header ──────────────────────────────────────────────────────────────────
echo.
echo ╔══════════════════════════════════════════════╗
echo ║  Claude ^-^> DeepSeek Proxy - Setup            ║
echo ╚══════════════════════════════════════════════╝
echo.
echo This script will configure everything needed to use
echo DeepSeek ^& Gemini Flash via Claude Desktop.
echo.

:: ── [1/9] Check prerequisites ──────────────────────────────────────────────
echo [1/9] Checking prerequisites...

where node >nul 2>&1
if %errorlevel% neq 0 (
    echo   ✗ Node.js is not installed.
    echo     Install it from https://nodejs.org (v18+)
    pause
    exit /b 1
)
echo   ✓ Node.js found

where openssl >nul 2>&1
if %errorlevel% neq 0 (
    echo   ✗ OpenSSL is not in PATH.
    echo     Install Git for Windows which includes OpenSSL
    pause
    exit /b 1
)
echo   ✓ OpenSSL found
echo.

:: ── [2/9] Choose LLM provider ─────────────────────────────────────────────
echo [2/9] Choose LLM provider
echo.
echo   Select the LLM provider for text generation:
echo.
echo   1. DeepSeek API (api.deepseek.com - Anthropic-compatible^)
echo      Free credits on signup, good performance
echo.
echo   2. OpenCode Go (opencode.ai - OpenAI-compatible^)
echo      Alternative provider, hosts DeepSeek models
echo.

set "LLM_PROVIDER="
set /p "LLM_PROVIDER=  Choose [1] DeepSeek or [2] OpenCode Go: "
if "!LLM_PROVIDER!"=="" set "LLM_PROVIDER=1"
if not "!LLM_PROVIDER!"=="1" if not "!LLM_PROVIDER!"=="2" (
    echo   ✗ Invalid choice. Please choose 1 or 2.
    pause
    exit /b 1
)

echo   ✓ Selected: !LLM_PROVIDER!
echo.

:: ── [3/9] API Keys ─────────────────────────────────────────────────────────
echo [3/9] Configure API keys
echo.

if "!LLM_PROVIDER!"=="2" (
    echo   LLM provider: OpenCode Go
    echo   -^> Get your API key at: https://opencode.ai
    echo.
    set /p "OPENCODE_KEY=  OpenCode API key: "
    if "!OPENCODE_KEY!"=="" (
        echo   ✗ OpenCode API key is required.
        pause
        exit /b 1
    )
) else (
    echo   LLM provider: DeepSeek API
    echo   -^> Get your API key at: https://platform.deepseek.com
    echo.
    set /p "DEEPSEEK_KEY=  DeepSeek API key (sk-...): "
    if "!DEEPSEEK_KEY!"=="" (
        echo   ✗ DeepSeek API key is required.
        pause
        exit /b 1
    )
)

echo.
echo   Gemini Flash 2.5 is used for image OCR (auto-detected^).
echo   -^> Get your free API key at: https://aistudio.google.com/apikey
echo     (1000 req/day free, no credit card required^)
echo.

set /p "GEMINI_KEY=  Gemini API key:            "
if "!GEMINI_KEY!"=="" (
    echo   ✗ Gemini API key is required.
    pause
    exit /b 1
)

:: Write .env based on provider choice
if "!LLM_PROVIDER!"=="2" (
    (
echo # Claude DeepSeek Proxy -- API keys
echo # Generated by setup.bat on %date% %time%
echo.
echo # OpenCode Go API Key (https://opencode.ai^)
echo OPENCODE_API_KEY=!OPENCODE_KEY!
echo.
echo # Google Gemini API Key (https://aistudio.google.com/apikey -- free tier^)
echo GEMINI_API_KEY=!GEMINI_KEY!
    ) > "%ENV_FILE%"
) else (
    (
echo # Claude DeepSeek Proxy -- API keys
echo # Generated by setup.bat on %date% %time%
echo.
echo # DeepSeek API Key (https://platform.deepseek.com^)
echo DEEPSEEK_API_KEY=!DEEPSEEK_KEY!
echo.
echo # Google Gemini API Key (https://aistudio.google.com/apikey -- free tier^)
echo GEMINI_API_KEY=!GEMINI_KEY!
    ) > "%ENV_FILE%"
)

echo   ✓ .env file created
echo.

:: ── [3/8] Generate TLS certificates ────────────────────────────────────────
echo [4/9] Generate TLS certificates...
powershell -ExecutionPolicy Bypass -File "%CERTS_DIR%generate-certs.ps1"
if %errorlevel% neq 0 (
    echo   ✗ Certificate generation failed.
    pause
    exit /b 1
)
echo   ✓ Certificates generated in certs\
echo.

:: ── [4/8] Install CA certificate ───────────────────────────────────────────
echo [5/9] Install CA certificate in system trust store...
powershell -ExecutionPolicy Bypass -File "%CERTS_DIR%install-ca.ps1"
if %errorlevel% neq 0 (
    echo   ✗ CA installation failed. Try running as Administrator.
    pause
    exit /b 1
)
echo   ✓ CA certificate installed
echo.

:: ── [5/8] Claude Desktop — manual steps ────────────────────────────────────
echo [5/9] Claude Desktop — manual configuration
echo.
echo   Now you need to do TWO things in Claude Desktop:
echo.
echo   1. Enable Developer Mode:
echo      Open Claude Desktop -^> Help -^> Troubleshooting
echo      -^> Enable Developer Mode
echo.
echo   2. Configure third-party inference:
echo      Go to Developer -^> Configure third-party inference
echo      - Inference provider: Gateway
echo      - Gateway base URL:   https://localhost:8877
echo      - Gateway API key:    proxy-local-key
echo      - Models to add:
echo        - claude-sonnet-4-5  (label: sonnet 4.5)
echo        - claude-opus-4-7   (label: claude opus 4.7)
echo      Click 'Apply locally'
echo.
echo   WARNING: Do NOT sign in to claude.ai -- stay on the login screen.
echo.
pause
echo.

:: ── [6/8] Write developer_settings.json ────────────────────────────────────
echo [6/9] Writing developer settings...

:: Determine Claude Desktop paths on Windows
set "CLAUDE_DIR=%APPDATA%\Claude"
set "CLAUDE_3P_DIR=%LOCALAPPDATA%\Claude-3p"

if not exist "%CLAUDE_DIR%" mkdir "%CLAUDE_DIR%"
if not exist "%CLAUDE_3P_DIR%" mkdir "%CLAUDE_3P_DIR%"

:: Write JSON to both locations
(
echo {
echo   "allowDevTools": true,
echo   "gateway": {
echo     "url": "https://localhost:8877"
echo   }
echo }
) > "%CLAUDE_DIR%\developer_settings.json"
echo   ✓ %CLAUDE_DIR%\developer_settings.json

(
echo {
echo   "allowDevTools": true,
echo   "gateway": {
echo     "url": "https://localhost:8877"
echo   }
echo }
) > "%CLAUDE_3P_DIR%\developer_settings.json"
echo   ✓ %CLAUDE_3P_DIR%\developer_settings.json
echo.

:: ── [7/8] Write 3P configLibrary ───────────────────────────────────────────
echo [7/9] Writing third-party inference config...

set "CONFIG_DIR=%CLAUDE_3P_DIR%\configLibrary"
if not exist "%CONFIG_DIR%" mkdir "%CONFIG_DIR%"

set "CONFIG_ID=claude-deepseek-proxy"

:: _meta.json
(
echo {"applied":"%CONFIG_ID%"}
) > "%CONFIG_DIR%\_meta.json"

:: Config JSON
(
echo {
echo   "inferenceProvider": "gateway",
echo   "inferenceGatewayBaseUrl": "https://localhost:8877",
echo   "inferenceGatewayApiKey": "proxy-local-key",
echo   "inferenceGatewayAuthScheme": "bearer",
echo   "modelDiscoveryEnabled": "false",
echo   "inferenceModels": "[{\"name\":\"claude-sonnet-4-5\",\"labelOverride\":\"sonnet 4.5\",\"anthropicFamilyTier\":\"sonnet\",\"isFamilyDefault\":true},{\"name\":\"claude-opus-4-7\",\"labelOverride\":\"claude opus 4.7\",\"anthropicFamilyTier\":\"opus\"}]"
echo }
) > "%CONFIG_DIR%\%CONFIG_ID%.json"
echo   ✓ %CONFIG_DIR%\%CONFIG_ID%.json
echo.

:: ── [8/8] Start the proxy ──────────────────────────────────────────────────
echo [8/9] Starting the proxy...

:: Check if already running
tasklist /fi "imagename eq node.exe" 2>nul | find /i "node.exe" >nul
if %errorlevel% equ 0 (
    echo   ! Proxy may already be running. Kill it first if needed:
    echo     taskkill /f /im node.exe
)

cd /d "%SCRIPT_DIR%"
start "Claude DeepSeek Proxy" /MIN cmd /c "node proxy\server.js"
echo   ✓ Proxy started on https://localhost:8877
echo.

:: ── Verification ───────────────────────────────────────────────────────────
echo ═══ Verification ═══════════════════════════════════════
echo.

:: Test 1: TLS
echo   Testing TLS connectivity...
curl -sk https://localhost:8877/ >nul 2>&1
if %errorlevel% equ 0 (
    echo   ✓ TLS OK
) else (
    echo   ✗ TLS FAIL - is the proxy running?
)
echo.

:: ── Done ────────────────────────────────────────────────────────────────────
echo ╔══════════════════════════════════════════════╗
echo ║  Setup complete!                            ║
echo ╚══════════════════════════════════════════════╝
echo.
echo   Next steps:
echo   1. Quit Claude Desktop completely (from tray too)
echo   2. Reopen Claude Desktop
echo   3. Select 'sonnet 4.5' or 'claude opus 4.7' from the picker
echo   4. Start chatting!
echo.
echo   Stop proxy:  Close the proxy window or taskkill /f /im node.exe
echo   Restart:     Run start.bat
echo.

pause
