@echo off
chcp 65001 >nul
setlocal enabledelayedexpansion
title Claude DeepSeek Proxy - Setup

:: =============================================================================
:: Claude → DeepSeek Proxy - Interactive Setup (Windows)
:: =============================================================================

:: ── Paths ───────────────────────────────────────────────────────────────────
set "SCRIPT_DIR=%~dp0"
set "ENV_FILE=%SCRIPT_DIR%.env"
set "CERTS_DIR=%SCRIPT_DIR%certs"

:: ── Header ──────────────────────────────────────────────────────────────────
echo.
echo ╔══════════════════════════════════════════════╗
echo ║  Claude ^-^> DeepSeek Proxy - Setup            ║
echo ╚══════════════════════════════════════════════╝
echo.
echo This script will configure everything needed to use
echo DeepSeek ^& Gemini Flash via Claude Desktop.
echo.

:: ── [1/9] Check prerequisites ──────────────────────────────────────────────
echo [1/9] Checking prerequisites...

where node >nul 2>&1
if %errorlevel% neq 0 (
    echo   ! Node.js not found. Trying to install automatically...
    echo.
    :: Try winget first (available on Windows 10 1709+ and Windows 11)
    where winget >nul 2>&1
    if %errorlevel% equ 0 (
        echo   Downloading Node.js LTS via winget...
        winget install --id OpenJS.NodeJS.LTS --silent --accept-package-agreements --accept-source-agreements
        if %errorlevel% neq 0 (
            echo   ✗ winget install failed.
            goto :node_manual
        )
        :: Refresh PATH so node is visible in this session
        for /f "tokens=*" %%i in ('powershell -NoProfile -Command "[System.Environment]::GetEnvironmentVariable(\"PATH\",\"Machine\")"') do set "PATH=%%i;%PATH%"
        where node >nul 2>&1
        if %errorlevel% neq 0 (
            echo   ✓ Node.js installed. Please close and reopen this window, then run setup.bat again.
            pause
            exit /b 0
        )
        echo   ✓ Node.js installed successfully
    ) else (
        :node_manual
        echo   ✗ Could not install Node.js automatically.
        echo.
        echo     Please install Node.js manually:
        echo     https://nodejs.org/en/download  (choose Windows Installer, LTS version)
        echo.
        echo     After installing, close this window and run setup.bat again.
        pause
        exit /b 1
    )
)
echo   ✓ Node.js found
echo   (certificates generated via PowerShell - no OpenSSL needed)
echo.

:: ── [2/9] Choose LLM provider ─────────────────────────────────────────────
echo [2/9] Choose LLM provider
echo.
echo   Select the LLM provider for text generation:
echo.
echo   1. DeepSeek API (api.deepseek.com - Anthropic-compatible^)
echo      Free credits on signup, good performance
echo.
echo   2. OpenCode Go (opencode.ai - OpenAI-compatible^)
echo      Alternative provider, hosts DeepSeek models
echo.

set "LLM_PROVIDER="
set /p "LLM_PROVIDER=  Choose [1] DeepSeek or [2] OpenCode Go: "
if "!LLM_PROVIDER!"=="" set "LLM_PROVIDER=1"
if not "!LLM_PROVIDER!"=="1" if not "!LLM_PROVIDER!"=="2" (
    echo   ✗ Invalid choice. Please choose 1 or 2.
    pause
    exit /b 1
)

echo   ✓ Selected: !LLM_PROVIDER!
echo.

:: ── [3/9] API Keys ─────────────────────────────────────────────────────────
echo [3/9] Configure API keys
echo.

if "!LLM_PROVIDER!"=="2" (
    echo   LLM provider: OpenCode Go
    echo   -^> Get your API key at: https://opencode.ai
    echo.
    set /p "OPENCODE_KEY=  OpenCode API key: "
    if "!OPENCODE_KEY!"=="" (
        echo   ✗ OpenCode API key is required.
        pause
        exit /b 1
    )
) else (
    echo   LLM provider: DeepSeek API
    echo   -^> Get your API key at: https://platform.deepseek.com
    echo.
    set /p "DEEPSEEK_KEY=  DeepSeek API key (sk-...): "
    if "!DEEPSEEK_KEY!"=="" (
        echo   ✗ DeepSeek API key is required.
        pause
        exit /b 1
    )
)

echo.
echo   Gemini Flash 2.5 is used for image OCR (auto-detected^).
echo   -^> Get your free API key at: https://aistudio.google.com/apikey
echo     (1000 req/day free, no credit card required^)
echo.

set /p "GEMINI_KEY=  Gemini API key:            "
if "!GEMINI_KEY!"=="" (
    echo   ✗ Gemini API key is required.
    pause
    exit /b 1
)

:: Write .env based on provider choice
if "!LLM_PROVIDER!"=="2" (
    (
echo # Claude DeepSeek Proxy -- API keys
echo # Generated by setup.bat on %date% %time%
echo.
echo # OpenCode Go API Key (https://opencode.ai^)
echo OPENCODE_API_KEY=!OPENCODE_KEY!
echo.
echo # Google Gemini API Key (https://aistudio.google.com/apikey -- free tier^)
echo GEMINI_API_KEY=!GEMINI_KEY!
    ) > "%ENV_FILE%"
) else (
    (
echo # Claude DeepSeek Proxy -- API keys
echo # Generated by setup.bat on %date% %time%
echo.
echo # DeepSeek API Key (https://platform.deepseek.com^)
echo DEEPSEEK_API_KEY=!DEEPSEEK_KEY!
echo.
echo # Google Gemini API Key (https://aistudio.google.com/apikey -- free tier^)
echo GEMINI_API_KEY=!GEMINI_KEY!
    ) > "%ENV_FILE%"
)

echo   ✓ .env file created
echo.

:: ── [4/9] Generate TLS certificates ────────────────────────────────────────
echo [4/9] Generate TLS certificates...
powershell -ExecutionPolicy Bypass -File "%CERTS_DIR%\generate-certs.ps1"
if %errorlevel% neq 0 (
    echo   ✗ Certificate generation failed.
    pause
    exit /b 1
)
echo   ✓ Certificates generated in certs\
echo.

:: ── [5/9] Install CA certificate ───────────────────────────────────────────
echo [5/9] Install CA certificate in system trust store...
powershell -ExecutionPolicy Bypass -File "%CERTS_DIR%\install-ca.ps1"
if %errorlevel% neq 0 (
    echo   ✗ CA installation failed. Try running as Administrator.
    pause
    exit /b 1
)
echo   ✓ CA certificate installed
echo.

:: ── [6/9] Write developer_settings.json ────────────────────────────────────
echo [6/9] Writing developer settings...

set "CLAUDE_DIR=%APPDATA%\Claude"
set "CLAUDE_3P_DIR=%LOCALAPPDATA%\Claude-3p"

if not exist "%CLAUDE_DIR%" mkdir "%CLAUDE_DIR%"
if not exist "%CLAUDE_3P_DIR%" mkdir "%CLAUDE_3P_DIR%"

(
echo {
echo   "allowDevTools": true,
echo   "gateway": {
echo     "url": "https://localhost:8877"
echo   }
echo }
) > "%CLAUDE_DIR%\developer_settings.json"
echo   ✓ %CLAUDE_DIR%\developer_settings.json

(
echo {
echo   "allowDevTools": true,
echo   "gateway": {
echo     "url": "https://localhost:8877"
echo   }
echo }
) > "%CLAUDE_3P_DIR%\developer_settings.json"
echo   ✓ %CLAUDE_3P_DIR%\developer_settings.json
echo.

:: ── [7/9] Write 3P configLibrary ───────────────────────────────────────────
echo [7/9] Writing third-party inference config...

set "CONFIG_DIR=%CLAUDE_3P_DIR%\configLibrary"
if not exist "%CONFIG_DIR%" mkdir "%CONFIG_DIR%"
set "CONFIG_ID=claude-deepseek-proxy"

(
echo {"applied":"%CONFIG_ID%"}
) > "%CONFIG_DIR%\_meta.json"

(
echo {
echo   "inferenceProvider": "gateway",
echo   "inferenceGatewayBaseUrl": "https://localhost:8877",
echo   "inferenceGatewayApiKey": "proxy-local-key",
echo   "inferenceGatewayAuthScheme": "bearer",
echo   "modelDiscoveryEnabled": "false",
echo   "inferenceModels": "[{\"name\":\"claude-sonnet-4-5\",\"labelOverride\":\"sonnet 4.5\",\"anthropicFamilyTier\":\"sonnet\",\"isFamilyDefault\":true},{\"name\":\"claude-opus-4-7\",\"labelOverride\":\"claude opus 4.7\",\"anthropicFamilyTier\":\"opus\"}]"
echo }
) > "%CONFIG_DIR%\%CONFIG_ID%.json"
echo   ✓ %CONFIG_DIR%\%CONFIG_ID%.json
echo.

:: ── [8/9] Start the proxy ──────────────────────────────────────────────────
echo [8/9] Starting the proxy...

tasklist /fi "imagename eq node.exe" 2>nul | find /i "node.exe" >nul
if %errorlevel% equ 0 (
    echo   ! A node.exe process is already running - it may be the proxy.
)

cd /d "%SCRIPT_DIR%"
start "Claude DeepSeek Proxy" /MIN cmd /c "node proxy\server.js"

echo   Waiting for proxy to be ready...
timeout /t 3 /nobreak >nul

curl -sk https://localhost:8877/ >nul 2>&1
if %errorlevel% equ 0 (
    echo   ✓ Proxy running on https://localhost:8877
) else (
    echo   ✗ Proxy did not respond - check the proxy window for errors.
    pause
    exit /b 1
)
echo.

:: ── [9/9] Claude Desktop — manual configuration ─────────────────────────────
echo [9/9] Claude Desktop — manual configuration
echo.
echo   The proxy is now running. Open Claude Desktop and do TWO things:
echo.
echo   1. Enable Developer Mode:
echo      Help -^> Troubleshooting -^> Enable Developer Mode
echo.
echo   2. Configure third-party inference:
echo      Developer -^> Configure third-party inference
echo      - Inference provider:  Gateway
echo      - Gateway base URL:    https://localhost:8877
echo      - Gateway API key:     proxy-local-key
echo      - Models to add:
echo          claude-sonnet-4-5  (label: sonnet 4.5)
echo          claude-opus-4-7    (label: claude opus 4.7)
echo      Click 'Apply locally'
echo.
echo   WARNING: Do NOT sign in to claude.ai -- stay on the login screen.
echo.
pause
echo.

:: ── Auto-start at login ──────────────────────────────────────────────────────
echo   Would you like the proxy to start automatically at Windows login?
echo   (Recommended - otherwise you must run it manually each time)
echo.
set "AUTO_START="
set /p "AUTO_START=  Set up auto-start? [Y/n]: "
if "!AUTO_START!"=="" set "AUTO_START=Y"

if /i "!AUTO_START!"=="Y" (
    echo.
    echo   Setting up Task Scheduler task...
    set "TASK_NAME=ClaudeDeepSeekProxy"
    set "PROXY_CMD=node proxy\server.js"
    powershell -NoProfile -ExecutionPolicy Bypass -Command ^
        "$action  = New-ScheduledTaskAction -Execute 'node.exe' -Argument 'proxy\server.js' -WorkingDirectory '%SCRIPT_DIR%';" ^
        "$trigger = New-ScheduledTaskTrigger -AtLogOn;" ^
        "$settings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit ([TimeSpan]::Zero) -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1);" ^
        "Register-ScheduledTask -TaskName 'ClaudeDeepSeekProxy' -Action $action -Trigger $trigger -Settings $settings -RunLevel Highest -Force | Out-Null;" ^
        "Write-Host '  OK'"
    if %errorlevel% equ 0 (
        echo   ✓ Task registered: proxy will start automatically at every login
    ) else (
        echo   ✗ Could not register task. Try running setup.bat as Administrator.
    )
) else (
    echo   Skipped. To start the proxy manually run:
    echo     start.bat   (or:  node proxy\server.js)
)
echo.

:: ── Done ────────────────────────────────────────────────────────────────────
echo ╔══════════════════════════════════════════════╗
echo ║  Setup complete!                             ║
echo ╚══════════════════════════════════════════════╝
echo.
echo   Next steps:
echo   1. Quit Claude Desktop completely (from tray too)
echo   2. Reopen Claude Desktop
echo   3. Select 'sonnet 4.5' or 'claude opus 4.7' from the model picker
echo   4. Start chatting!
echo.
echo   Stop proxy:    taskkill /f /im node.exe
echo   Remove task:   schtasks /delete /tn ClaudeDeepSeekProxy /f
echo.

pause
