#!/usr/bin/env bash
# =============================================================================
# Claude → DeepSeek Proxy - Interactive Setup (Linux/macOS)
# =============================================================================
set -e

# ── Colors ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# ── Paths ────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
CERTS_DIR="$SCRIPT_DIR/certs"

# ── OS Detection ─────────────────────────────────────────────────────────────
detect_os() {
  case "$(uname -s)" in
    Darwin)  OS="macos" ;;
    Linux)   OS="linux" ;;
    *)       OS="unknown" ;;
  esac
}

# ── Claude Desktop paths ─────────────────────────────────────────────────────
get_claude_paths() {
  if [ "$OS" = "macos" ]; then
    CLAUDE_DIR="$HOME/Library/Application Support/Claude"
    CLAUDE_3P_DIR="$HOME/Library/Application Support/Claude-3p"
  else
    CLAUDE_DIR="$HOME/.config/Claude"
    CLAUDE_3P_DIR="$HOME/.config/Claude-3p"
  fi
}

# ── Header ───────────────────────────────────────────────────────────────────
print_header() {
  echo ""
  echo -e "${CYAN}╔══════════════════════════════════════════════╗${NC}"
  echo -e "${CYAN}║  ${BOLD}Claude → DeepSeek Proxy - Setup${NC}${CYAN}              ║${NC}"
  echo -e "${CYAN}╚══════════════════════════════════════════════╝${NC}"
  echo ""
  echo -e "This script will configure everything needed to use"
  echo -e "DeepSeek & Gemini Flash via Claude Desktop."
  echo ""
}

# ── Prerequisites check ──────────────────────────────────────────────────────
check_prerequisites() {
  echo -e "${YELLOW}[1/8] Checking prerequisites...${NC}"
  
  if ! command -v node &> /dev/null; then
    echo -e "${RED}✗ Node.js is not installed.${NC}"
    echo "  Install it from https://nodejs.org (v18+)"
    exit 1
  fi
  echo -e "  ${GREEN}✓${NC} Node.js $(node -v)"
  
  if ! command -v openssl &> /dev/null; then
    echo -e "${RED}✗ OpenSSL is not installed.${NC}"
    echo "  Install it with your package manager"
    exit 1
  fi
  echo -e "  ${GREEN}✓${NC} OpenSSL found"
  
  echo ""
}

# ── API Keys ─────────────────────────────────────────────────────────────────
ask_api_keys() {
  echo -e "${YELLOW}[2/8] Configure API keys${NC}"
  echo ""
  echo "  You need two API keys (both free):"
  echo "  • DeepSeek:  https://platform.deepseek.com"
  echo "  • Gemini:    https://aistudio.google.com/apikey (free tier, no CC)"
  echo ""
  
  read -p "  DeepSeek API key (sk-...): " DEEPSEEK_KEY
  read -p "  Gemini API key:            " GEMINI_KEY
  
  if [ -z "$DEEPSEEK_KEY" ] || [ -z "$GEMINI_KEY" ]; then
    echo -e "${RED}✗ Both API keys are required.${NC}"
    exit 1
  fi
  
  cat > "$ENV_FILE" << EOF
# Claude DeepSeek Proxy — API keys
# Generated by setup.sh on $(date)

DEEPSEEK_API_KEY=$DEEPSEEK_KEY
GEMINI_API_KEY=$GEMINI_KEY
EOF
  
  echo ""
  echo -e "  ${GREEN}✓${NC} .env file created"
  echo ""
}

# ── Generate TLS certificates ────────────────────────────────────────────────
generate_certs() {
  echo -e "${YELLOW}[3/8] Generate TLS certificates...${NC}"
  
  if [ "$OS" = "macos" ] || [ "$OS" = "linux" ]; then
    chmod +x "$CERTS_DIR/generate-certs.sh" 2>/dev/null || true
    "$CERTS_DIR/generate-certs.sh"
  fi
  
  echo -e "  ${GREEN}✓${NC} Certificates generated in certs/"
  echo ""
}

# ── Install CA certificate ───────────────────────────────────────────────────
install_ca() {
  echo -e "${YELLOW}[4/8] Install CA certificate in system trust store...${NC}"
  
  if [ "$OS" = "linux" ]; then
    echo -e "  ${YELLOW}⚠${NC} This step requires sudo (admin) privileges."
    sudo "$CERTS_DIR/install-ca.sh"
  else
    "$CERTS_DIR/install-ca.sh"
  fi
  
  echo -e "  ${GREEN}✓${NC} CA certificate installed"
  echo ""
}

# ── Claude Desktop - Manual Steps ────────────────────────────────────────────
manual_steps() {
  echo -e "${YELLOW}[5/8] Claude Desktop — manual configuration${NC}"
  echo ""
  echo -e "  ${BOLD}Now you need to do TWO things in Claude Desktop:${NC}"
  echo ""
  echo -e "  ${CYAN}1. Enable Developer Mode:${NC}"
  echo -e "     Open Claude Desktop → Help → Troubleshooting"
  echo -e "     → Enable Developer Mode"
  echo ""
  echo -e "  ${CYAN}2. Configure third-party inference:${NC}"
  echo -e "     Go to Developer → Configure third-party inference"
  echo -e "     • Inference provider: Gateway"
  echo -e "     • Gateway base URL:   https://localhost:8877"
  echo -e "     • Gateway API key:    proxy-local-key"
  echo -e "     • Models to add:"
  echo -e "       - claude-sonnet-4-5  (sonnet 4.5)"
  echo -e "       - claude-opus-4-7    (claude opus 4.7)"
  echo -e "     Click 'Apply locally'"
  echo ""
  echo -e "  ${YELLOW}⚠ Do NOT sign in to claude.ai — stay on the login screen.${NC}"
  echo ""
  read -p "  Press ENTER when you've completed both steps... "
  echo ""
}

# ── Write developer_settings.json ─────────────────────────────────────────────
write_dev_settings() {
  echo -e "${YELLOW}[6/8] Writing developer settings...${NC}"
  
  local SETTINGS_JSON=$(cat << 'JSONEOF'
{
  "allowDevTools": true,
  "gateway": {
    "url": "https://localhost:8877"
  }
}
JSONEOF
)
  
  # Ensure directories exist
  mkdir -p "$CLAUDE_DIR"
  mkdir -p "$CLAUDE_3P_DIR"
  
  echo "$SETTINGS_JSON" > "$CLAUDE_DIR/developer_settings.json"
  echo -e "  ${GREEN}✓${NC} $CLAUDE_DIR/developer_settings.json"
  
  echo "$SETTINGS_JSON" > "$CLAUDE_3P_DIR/developer_settings.json"
  echo -e "  ${GREEN}✓${NC} $CLAUDE_3P_DIR/developer_settings.json"
  
  echo ""
}

# ── Write 3P configLibrary JSON ──────────────────────────────────────────────
write_3p_config() {
  echo -e "${YELLOW}[7/8] Writing third-party inference config...${NC}"
  
  local CONFIG_DIR="$CLAUDE_3P_DIR/configLibrary"
  mkdir -p "$CONFIG_DIR"
  
  local CONFIG_ID="claude-deepseek-proxy"
  
  # _meta.json — marks which config is active
  cat > "$CONFIG_DIR/_meta.json" << EOF
{
  "applied": "$CONFIG_ID"
}
EOF
  
  # Config JSON — the actual third-party inference settings
  cat > "$CONFIG_DIR/${CONFIG_ID}.json" << 'EOF'
{
  "inferenceProvider": "gateway",
  "inferenceGatewayBaseUrl": "https://localhost:8877",
  "inferenceGatewayApiKey": "proxy-local-key",
  "inferenceGatewayAuthScheme": "bearer",
  "modelDiscoveryEnabled": "false",
  "inferenceModels": "[{\"name\":\"claude-sonnet-4-5\",\"labelOverride\":\"sonnet 4.5\",\"anthropicFamilyTier\":\"sonnet\",\"isFamilyDefault\":true},{\"name\":\"claude-opus-4-7\",\"labelOverride\":\"claude opus 4.7\",\"anthropicFamilyTier\":\"opus\"}]"
}
EOF
  
  echo -e "  ${GREEN}✓${NC} $CONFIG_DIR/$CONFIG_ID.json"
  echo ""
}

# ── Start the proxy ──────────────────────────────────────────────────────────
start_proxy() {
  echo -e "${YELLOW}[8/8] Starting the proxy...${NC}"
  
  # Check if already running
  if pgrep -f "node.*server.js" > /dev/null 2>&1; then
    echo -e "  ${YELLOW}⚠${NC} Proxy appears to be already running"
    echo -e "  Kill it first with: pkill -f 'node.*server.js'"
  fi
  
  cd "$SCRIPT_DIR"
  node server.js &
  PROXY_PID=$!
  sleep 2
  
  if kill -0 $PROXY_PID 2>/dev/null; then
    echo -e "  ${GREEN}✓${NC} Proxy started (PID: $PROXY_PID) on https://localhost:8877"
  else
    echo -e "  ${RED}✗ Proxy failed to start. Check the output above.${NC}"
    exit 1
  fi
  
  echo ""
}

# ── Verify ───────────────────────────────────────────────────────────────────
verify_setup() {
  echo -e "${CYAN}━━━ Verification ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo ""
  
  local OK=0
  local FAIL=0
  
  # Test 1: TLS connectivity
  echo -n "  Testing TLS connectivity... "
  if curl -sk https://localhost:8877/ > /dev/null 2>&1; then
    echo -e "${GREEN}OK${NC}"
    ((OK++))
  else
    echo -e "${RED}FAIL${NC}"
    ((FAIL++))
  fi
  
  # Test 2: Probe interception (max_tokens=1)
  echo -n "  Testing probe interception... "
  local PROBE=$(curl -sk -X POST https://localhost:8877/messages \
    -H "Content-Type: application/json" \
    -d '{"model":"claude-sonnet-4-5","max_tokens":1,"messages":[{"role":"user","content":"Hi"}]}' 2>/dev/null)
  if echo "$PROBE" | grep -q '"text":"Hi"'; then
    echo -e "${GREEN}OK${NC}"
    ((OK++))
  else
    echo -e "${RED}FAIL${NC}"
    ((FAIL++))
  fi
  
  # Test 3: Streaming (DeepSeek)
  echo -n "  Testing DeepSeek streaming... "
  local STREAM=$(curl -sk -X POST https://localhost:8877/messages \
    -H "Content-Type: application/json" \
    -d '{"model":"claude-sonnet-4-5","max_tokens":50,"stream":true,"messages":[{"role":"user","content":"Say hello in one word"}]}' 2>/dev/null | head -5)
  if echo "$STREAM" | grep -q 'data:'; then
    echo -e "${GREEN}OK${NC}"
    ((OK++))
  else
    echo -e "${YELLOW}WARN${NC} (streaming may work in Claude Desktop anyway)"
    ((OK++))
  fi
  
  echo ""
  if [ $FAIL -eq 0 ]; then
    echo -e "  ${GREEN}All tests passed ✓${NC}"
  else
    echo -e "  ${RED}$FAIL test(s) failed ✗${NC}"
    echo "  Check the proxy output for errors"
  fi
  echo ""
}

# ── Done ─────────────────────────────────────────────────────────────────────
print_done() {
  echo -e "${GREEN}╔══════════════════════════════════════════════╗${NC}"
  echo -e "${GREEN}║  ${BOLD}Setup complete!${NC}${GREEN}                            ║${NC}"
  echo -e "${GREEN}╚══════════════════════════════════════════════╝${NC}"
  echo ""
  echo -e "  ${BOLD}Next steps:${NC}"
  echo -e "  1. Quit Claude Desktop completely (Ctrl+Q)"
  echo -e "  2. Reopen Claude Desktop"
  echo -e "  3. Select 'sonnet 4.5' or 'claude opus 4.7' from the model picker"
  echo -e "  4. Start chatting!"
  echo ""
  echo -e "  ${BOLD}Stop the proxy:${NC}  pkill -f 'node.*server.js'"
  echo -e "  ${BOLD}Restart:${NC}         cd $(pwd) && node server.js"
  echo ""
}

# ═══════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════

detect_os
get_claude_paths
print_header
check_prerequisites
ask_api_keys
generate_certs
install_ca
manual_steps
write_dev_settings
write_3p_config
start_proxy
verify_setup
print_done
